version: '3'

services: 
  nginx:
    build: './nginx'
    volumes:

      - ./nginx/test_cpu.txt:/test_cpu.txt
      - ./nginx/access.log:/var/log/nginx/access.log
      - ./nginx/error.log:/var/log/nginx/error.log
     


    ports:
      - 8080:80
      - 443:443
    depends_on:
      - php

  php:
    build: './php'
    ports:
      - 8081:8081
    volumes:
      - ./php/public:/var/www/html
