version: '3'

services: 
  nginx:
    build: './nginx'
    volumes:
      - ./:/var/log/nginx
#      - ./nginx/conf/default:/etc/nginx/sites-available/default
#      - ./nginx/conf/default:/etc/nginx/sites-enabled/default
#      - ./nginx/cert:/etc/nginx
    ports:
      - 8080:80
      - 443:443
    depends_on:
      - php

  php:
    build: './php'
    ports:
      - 8081:8081
    volumes:
      - ./:/var/www/html
   
