version: '3'

services: 
  nginx:
    build: './nginx'
    volumes:

#      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
#      - ./nginx/nginx-index.html:/var/www/html/nginx-index.html
#      - ./nginx/cert/fullchain.pem:/etc/nginx/fullchain.pem
#      - ./nginx/cert/privkey.pem:/etc/nginx/privkey.pem
      - ./nginx/test_cpu.txt:/test_cpu.txt
      - ./nginx/access.log:/var/log/nginx/access.log
      - ./nginx/error.log:/var/log/nginx/error.log
      - ./nginx/music.mp3:/tmp/music.mp3     
      - ./nginx/test_log.sh:/tmp/test_log.sh
      - ./nginx/400.log:/tmp/400.log
      - ./nginx/500/log:/tmp/500/log
      - ./nginx/cat_log.log:/tmp/cat_log.log
      - ./nginxclear_cat_log.log:/tmp/clear_cat_log.log
      - ./test_log.txt:/tmp/test_log.txt
    command: ["bin/sh", "/tmp/test_log.sh"]

    ports:
      - 8080:80
      - 443:443
    depends_on:
      - php

  php:
    build: './php'
    ports:
      - 8081:8081
    volumes:
      - ./php/public:/var/www/html
