version: '3'

services: 
  nginx:
    build: './nginx'
    volumes:

      - ./bash:/var/log/nginx
#      - ./bash/access.log:/var/log/nginx/access.log
#      - ./bash/error.log:/var/log/nginx/error.log
      - ./nginx/cert/privkey.pem:/etc/nginx/privkey.pem
      - ./nginx/404.html:/usr/share/nginx/html/404.html
      - ./nginx/music.mp3:/tmp/music.mp3     


    ports:
      - 8080:80
      - 443:443
    depends_on:
      - php

  php:
    build: './php'
    ports:
      - 8081:8081
    volumes:
      - ./php/public:/var/www/html

  bash:
    build: './bash'
    
    volumes:

      - ./bash/test_cpu.txt:/test_cpu.txt
#      - ./bash/access.log:/var/log/nginx/access.log
#      - ./bash/error.log:/var/log/nginx/error.log

      - ./bash:/tmp

#      - ./bash/400.log:/tmp/400.log
#      - ./bash/500/log:/tmp/500/log
#      - ./bash/cat_log.log:/tmp/cat_log.log
#      - ./bash/clear_cat_log.log:/tmp/clear_cat_log.log
#      - ./bash/test_log.txt:/tmp/test_log.txt

    command: ["bin/sh", "/tmp/test_log.sh"]

    restart: always
  
